version: '3'
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27016:27017"
    # 容器启动时需要的参数配置
    command: "--replSet rs0 --bind_ip_all"

networks:
  default:
    external:
      name: my_default

# 进入容器初始化副本集执行 mongo --host mongo --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongo:27017"}]})'
# 进入容器查看副本集状态执行 mongo --host mongo --eval 'rs.status()'