// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ken/hello.proto

package ken

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringMessage struct {
	// @required
	// valid:"required,in(aaa|bbb)" xml:"id,omitempty"
	// 注释
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"      valid:"required,in(aaa|bbb)" xml:"id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"       valid:"required,in(aaa|bbb)" xml:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb844950f32c8dae, []int{0}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// 会员
type StringMessage_Member struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"       valid:"required,in(aaa|bbb)" xml:"id,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"        valid:"required,in(aaa|bbb)" xml:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage_Member) Reset()         { *m = StringMessage_Member{} }
func (m *StringMessage_Member) String() string { return proto.CompactTextString(m) }
func (*StringMessage_Member) ProtoMessage()    {}
func (*StringMessage_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb844950f32c8dae, []int{0, 0}
}

func (m *StringMessage_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage_Member.Unmarshal(m, b)
}
func (m *StringMessage_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage_Member.Marshal(b, m, deterministic)
}
func (m *StringMessage_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage_Member.Merge(m, src)
}
func (m *StringMessage_Member) XXX_Size() int {
	return xxx_messageInfo_StringMessage_Member.Size(m)
}
func (m *StringMessage_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage_Member.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage_Member proto.InternalMessageInfo

func (m *StringMessage_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StringMessage_Member) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"   valid:"required,in(aaa|bbb)" xml:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb844950f32c8dae, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "blogrpc.ken.StringMessage")
	proto.RegisterType((*StringMessage_Member)(nil), "blogrpc.ken.StringMessage.Member")
	proto.RegisterType((*User)(nil), "blogrpc.ken.User")
}

func init() {
	proto.RegisterFile("ken/hello.proto", fileDescriptor_fb844950f32c8dae)
}

var fileDescriptor_fb844950f32c8dae = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x4e, 0xcd, 0xd3,
	0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0xca, 0xc9,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0xcb, 0x4e, 0xcd, 0x53, 0xaa, 0xe1, 0xe2, 0x0d, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc,
	0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x54, 0xb9, 0x58, 0x42,
	0x8b, 0x53, 0x8b, 0x24, 0x98, 0x14, 0x18, 0x35, 0xb8, 0x8d, 0x04, 0xf5, 0x90, 0x8c, 0xd0, 0x03,
	0x49, 0x04, 0x81, 0xa5, 0xa5, 0xf4, 0xb8, 0xd8, 0x7c, 0x53, 0x73, 0x93, 0x52, 0x8b, 0x84, 0x84,
	0xb8, 0x58, 0xfc, 0x12, 0x73, 0x61, 0xa6, 0x80, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x89, 0xe9, 0xa9,
	0x60, 0x33, 0x98, 0x83, 0x40, 0x4c, 0x25, 0x25, 0x88, 0xb1, 0x42, 0x52, 0x5c, 0x1c, 0xa5, 0xc5,
	0xa9, 0x45, 0x48, 0x3a, 0xe0, 0x7c, 0x27, 0xd6, 0x28, 0xe6, 0xec, 0xd4, 0xbc, 0x24, 0x36, 0xb0,
	0xe3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xb0, 0xb0, 0xad, 0xcf, 0x00, 0x00, 0x00,
}
