#! /bin/bash -e
#docker ps --format {{.Names}}
start() {
  local containerNames=(
scrm-infras-mongodb-1
scrm-blogrpc-account-1
scrm-infras-redis-1
  )
     for name in ${containerNames[@]};do
        docker start $name
     done
}

start
