#! /bin/bash -e
#docker ps --format {{.Names}}
start() {
  local containerNames=(
my-infras-mongodb-1
my-blogrpc-account-1
my-infras-redis-1
  )
     for name in ${containerNames[@]};do
        docker start $name
     done
}

start
