#! /bin/bash -e
WORK_DIR=${WORK_DIR:-`cd ${0%/*};pwd`}
DOCKER_GO_PATH=${DOCKER_GO_PATH-"/srv/go"} # Only used to build proto files
DOCKER_PROTO_PATH=${DOCKER_GO_PATH}/src/blogrpc/proto
REGISTRY_HOST=${REGISTRY_HOST:-"registry.ap-southeast-1.aliyuncs.com"} # 阿里云容器镜像服务| 新加坡：https://cr.console.aliyun.com/ap-southeast-1/instances
ENV=${ENV:-local}
PROTO_BUILDER_IMAGE=${REGISTRY_HOST}/yhhnamespace/tool-protoc-v2:${ENV}
GEN_STUB_COMMAND="./docker-gen-stub"

[[ -n $1 ]] && GEN_STUB_COMMAND="${GEN_STUB_COMMAND} $1 $2 $3"

docker pull ${PROTO_BUILDER_IMAGE}

docker run --rm -v ${WORK_DIR}:${DOCKER_PROTO_PATH} \
  -w ${DOCKER_PROTO_PATH} \
  -e "GOPATH=${DOCKER_GO_PATH}" \
  ${PROTO_BUILDER_IMAGE} ${GEN_STUB_COMMAND}