apiVersion: batch/v1
kind: Job
metadata:
  name: echo-job
spec:
  template:
    spec:
      containers:
        - name: echo-container
          image: busybox
          command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never