// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"blogrpc/practice/urfavecli/cmd"
	"blogrpc/practice/urfavecli/router"
	"github.com/google/wire"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func initApp() (cli.Commands, func()) {
	cmd1Router := router.NewCmd1Router()
	cmd1 := cmd.NewCmd1(cmd1Router)
	cmd2Router := router.NewCmd2Router()
	cmd2 := cmd.NewCmd2(cmd2Router)
	commands := &cmd.Commands{
		Cmd1: cmd1,
		Cmd2: cmd2,
	}
	cliCommands := cmd.NewCommands(commands)
	return cliCommands, func() {
	}
}

// wire.go:

var providerSet = wire.NewSet(router.NewCmd1Router, router.NewCmd2Router, cmd.ProviderSet)
