#!/bin/bash

host=$(ifconfig eth0 | grep 'inet addr' | cut -d ':' -f2 | cut -d ' ' -f1)

# Constant
#
# SHORT_SERVICE_NAME is the short service name (member, coupon ...)
SHORT_SERVICE_NAME=$(ls /app | grep -v "src")
# HOST is the service running host
HOST=${HOST:-$host}
# HOST is the service listening port
PORT=${PORT:-1701}
# ENV is current environment
ENV=${ENV:-production}

cd /app/$SHORT_SERVICE_NAME
echo "Service ${SHORT_SERVICE_NAME} is starting at ${HOST}:${PORT} in env ${ENV}"
# 注意：dlv 修改过源码，在 main 函数里加了一行 signal.Ignore(syscall.SIGHUP)，否则服务会起不来。
dlv exec ./${SHORT_SERVICE_NAME} --headless=true --accept-multiclient --continue --listen=:40000 --api-version=2 -- --env=${ENV} --port=${PORT} --host=${HOST}
